### ISSUE TITLE
Dependencies problems

### ISSUE THREAD

**Issue by davide221** [IdoGalil/People-counting-system#9]
Can you specify which version of python are you using? Are the requirements updated? I'm having some problem with tensorflow and cuda

**Comment by Nouman945** [comment]
Were you able to figure out the python and dependencies versions?

**Comment by IdoGalil** [comment]
I think the Python version used was 3.6.10.
All the requirements were updated at the time the project was deployed. The code hasn't changed since.

**Comment by Nouman945** [comment]
The Keras Version is Also not mentioned in the Repository Readme and requirements.txt file. If you can share the version I can update the readme for the complete steps to setup the environment and contribute to it. That would be very helpful.

**Comment by IdoGalil** [comment]
> Also, the Keras and h5py Versions are not mentioned in the Repository Readme and requirements.txt file. If you can share the version I can update the readme for the complete steps to setup the environment and contribute to it. That would be very helpful.

Unfortunately, I am unable to find the specific versions used.

**Comment by Nouman945** [comment]
Thankyou @IdoGalil. Also, I think the Cuda version mentioned (9.0) is not right. As tensorflow_gpu-1.14.0 support CUDA version 10. As can be checked from here. 

https://www.tensorflow.org/install/source_windows#gpu:~:text=tensorflow_gpu%2D1.14.0

Is it possible to check this for you now?

**Comment by IdoGalil** [comment]
> Thankyou @IdoGalil. Also, I think the Cuda version mentioned (9.0) is not right. As tensorflow_gpu-1.14.0 support CUDA version 10. As can be checked from here.
> 
> https://www.tensorflow.org/install/source_windows#gpu:~:text=tensorflow_gpu%2D1.14.0
> 
> Is it possible to check this for you now?

While it's true tensorflow_gpu-1.14.0 supports CUDA 10, the version used for this project was CUDA 9.0. It is possible the project could run with CUDA 10 as well, but this wasn't checked.
